
// SAGA -> RUDUX
export const AT_DISPLAY_ACTION = 'AT_DISPLAY_ACTION';
export const AT_DB_OPEN_SQLITE_START = 'AT_SQLITE_DB_OPEN_START';
export const AT_DB_OPEN_SQLITE_SUCCESS = 'AT_SQLITE_DB_OPEN_SUCCESS';
export const AT_CRUD_READ_GLOBAL_SQLITE_START = 'AT_CRUD_READ_GLOBAL_SQLITE_START';
export const AT_CRUD_READ_GLOBAL_SQLITE_SUCCESS = 'AT_CRUD_READ_GLOBAL_SQLITE_SUCCESS';

export const AT_CRUD_READ_cat_content_types_SQLITE_START = 'AT_CRUD_READ_cat_content_types_SQLITE_START';
export const AT_CRUD_READ_cat_content_types_SQLITE_SUCCESS = 'AT_CRUD_READ_cat_content_types_SQLITE_SUCCESS';


export const AT_CRUD_EXEC = 'AT_CRUD_EXEC';
export const AT_CRUD_EXEC_SUCCESS = 'AT_CRUD_EXEC_SUCCESS';


// DIRECT RUDUX

// OTHER
export const IS_LOADING = 'IS_LOADING...';
